[package]
name = "gdck-format"
description = "GDScript formatter (in development)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true

[dependencies]
gdck-config.workspace = true
gdck-syntax.workspace = true

[lints]
workspace = true
